---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  chef_omnibus_install_options: -P chefdk
  chef_omnibus_root: /opt/chefdk

verifier:
  ruby_bindir: /opt/chefdk/embedded/bin

platforms:
  - name: ubuntu-14.04
  - name: centos-6.7

suites:
  - name: ubuntu
    run_list:
      - "recipe[essentials::ubuntu]"
    attributes:
  - name: centos
    run_list:
      - "recipe[essentials::centos]"
    attributes:
