---
driver:
  name: vagrant

# verifier:
#   ruby_bindir: /opt/chefdk/embedded/bin
#   busser_bin: /home/vagrant/.chefdk/gem/ruby/2.1.0/bin/busser
#   root_path: /home/vagrant/.chefdk/gem/ruby/2.1.0

provisioner:
  name: chef_zero
  # chef_omnibus_install_options: -P chefdk
  # chef_omnibus_root: /opt/chefdk

platforms:
  - name: ubuntu-14.04
  - name: centos-6.5

suites:
  - name: ubuntu
    run_list:
      - "recipe[essentials::ubuntu]"
    attributes:
  - name: centos
    run_list:
      - "recipe[essentials::centos]"
    attributes:
