---
driver:
  name: vagrant

verifier:
  name: inspec

transport:
  username: root
  ssh_key: <%= ENV['TRAINING_AWS_KEYPAIR'] %>

platforms:
  - name: centos-6.7
  - name: AMI-centos-6.7
    driver_plugin: ec2
    driver_config:
      aws_ssh_key_id: training-ec2-keypair.pem
      image_id: ami-c10044a4
  - name: centos-7.1

suites:
  - name: essentials
    run_list:
      - "recipe[workstations::essentials]"
    attributes:
  - name: compliance
    run_list:
      - "recipe[workstations::compliance]"
    attributes:
  - name: tdd_cookbook_development
    run_list:
      - "recipe[workstations::tdd_cookbook_development]"
    attributes:
  - name: workshop_tomcat
    run_list:
      - "recipe[workstations::workshop_tomcat]"
    attributes:
