---
driver:
  name: vagrant

provisioner:
   name: chef_solo

verifier:
  name: inspec

transport:
  username: root

platforms:
  - name: centos-7.3
  - name: AMI-centos-6.7
    driver_plugin: ec2
    driver_config:
      aws_ssh_key_id: training-ec2-keypair
      image_id: ami-c10044a4
    transport:
      ssh_key: <%= ENV['TRAINING_AWS_KEYPAIR'] %>


suites:
  - name: essentials
    run_list:
      - "recipe[workstations::essentials]"
    attributes:
  - name: compliance
    run_list:
      - "recipe[workstations::compliance]"
    attributes:
  - name: tdd_cookbook_development
    run_list:
      - "recipe[workstations::tdd_cookbook_development]"
    attributes:
  - name: extending_cookbooks
    run_list:
      - "recipe[workstations::extending_cookbooks]"
    attributes:
